//команды смертных
#include "../../modules/player_commands/jobs_commands/dalnoboy.inc"
#include "../../modules/player_commands/stat.inc"
#include "../../modules/player_commands/pay.inc"
#include "../../modules/player_commands/vehcol.inc"
#include "../../modules/player_commands/skin.inc"
#include "../../modules/player_commands/sw.inc"
#include "../../modules/player_commands/st.inc"
#include "../../modules/player_commands/getv.inc"

//команды админов
#include "../../modules/admin_commands/all_adm_cmd.inc"